# Basic workflow for NestJS CI/CD

name: NestJS CI pipeline

# Controls when the workflow will run
on:
  push:
    branches: ["main"]

# Workflow jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Required permissions for GitHub OIDC / Workload Identity Federation
    permissions:
      contents: read
      id-token: write

    steps:
      # 1. Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - id: auth
        name: Authentication to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: mygithubcicd@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      # 3. Authenticate Docker with Google Artifact Registry
      - name: Docker auth
        run: |
          echo '${{ steps.auth.outputs.access_token }}' | \
            docker login \
            -u oauth2accesstoken \
            --password-stdin \
            https://us-central1-docker.pkg.dev

      # 4. Build Docker image
      - name: Build Container
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nextjs-repo/app:${{ github.sha }} .

      # 5. Push Docker image to Artifact Registry
      - name: Push Container
        run: |
          docker push \
            us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/nextjs-repo/app:latest

      # CD pipeline
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@v2

        with:
          cluster_name: nextjs-cluster
          location: us-central1

      - name: Deploy to GKE
        run: |
         kubectl apply -f k8s/deployment.yaml
        #  kubectl apply -f k8s/service.yaml
        #  kubectl rollout status deployment/nextjs-app
         